-- Migration: Add Videos and Podcasts tables
-- Run this in Supabase SQL Editor

-- 1. Create Videos Table
CREATE TABLE IF NOT EXISTS public.videos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    summary text, -- Description
    video_url text NOT NULL,
    image_url text, -- Thumbnail
    site_name text, -- Channel or Source
    date date DEFAULT CURRENT_DATE,
    industry_id uuid REFERENCES public.industries(id),
    search_vector tsvector,
    created_at timestamp with time zone DEFAULT now(),
    likes_count bigint DEFAULT 0,
    saves_count bigint DEFAULT 0,
    views_count bigint DEFAULT 0,
    duration_seconds integer
);

-- 2. Create Podcasts Table
CREATE TABLE IF NOT EXISTS public.podcasts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    summary text, -- Description
    audio_url text NOT NULL,
    image_url text, -- Cover Art
    site_name text, -- Host or Network
    date date DEFAULT CURRENT_DATE,
    industry_id uuid REFERENCES public.industries(id),
    search_vector tsvector,
    created_at timestamp with time zone DEFAULT now(),
    likes_count bigint DEFAULT 0,
    saves_count bigint DEFAULT 0,
    views_count bigint DEFAULT 0,
    duration_seconds integer
);

-- 3. Add Indexes for Search
CREATE INDEX IF NOT EXISTS videos_search_idx ON public.videos USING GIN (search_vector);
CREATE INDEX IF NOT EXISTS podcasts_search_idx ON public.podcasts USING GIN (search_vector);

-- 4. Create Trigger Function for Automatic Vector Updates (Reusable)
CREATE OR REPLACE FUNCTION public.handle_new_media_search_vector()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  NEW.search_vector := to_tsvector('english', 
    COALESCE(NEW.title, '') || ' ' || 
    COALESCE(NEW.summary, '') || ' ' || 
    COALESCE(NEW.site_name, '')
  );
  RETURN NEW;
END;
$$;

-- 5. Attach Triggers
DROP TRIGGER IF EXISTS tsvector_videos_trigger ON public.videos;
CREATE TRIGGER tsvector_videos_trigger
BEFORE INSERT OR UPDATE ON public.videos
FOR EACH ROW EXECUTE FUNCTION public.handle_new_media_search_vector();

DROP TRIGGER IF EXISTS tsvector_podcasts_trigger ON public.podcasts;
CREATE TRIGGER tsvector_podcasts_trigger
BEFORE INSERT OR UPDATE ON public.podcasts
FOR EACH ROW EXECUTE FUNCTION public.handle_new_media_search_vector();

-- 6. Enable RLS (Secure by default)
ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.podcasts ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Enable read access for authenticated users" ON public.videos FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public.podcasts FOR SELECT TO authenticated USING (true);

-- Optional: Insert dummy data for testing
INSERT INTO public.videos (title, summary, video_url, site_name, date)
VALUES 
('The Future of AI in 2026', 'An in-depth look at how artificial intelligence is reshaping industries.', 'https://youtube.com/watch?v=dummy1', 'Tech Explained', CURRENT_DATE)
ON CONFLICT DO NOTHING;

INSERT INTO public.podcasts (title, summary, audio_url, site_name, date)
VALUES 
('Tech Talk Daily: Quantum Computing', 'Is quantum supremacy finally here? We discuss the latest breakthroughs.', 'https://spotify.com/episode/dummy1', 'Daily Tech', CURRENT_DATE)
ON CONFLICT DO NOTHING;
